stages:
  - test
  - name: deploy
    #if: branch = master

language: python

install:
  - pip install coverage
script:
  # run tests with coverage
  - coverage run tests/run_tests.py
  - coverage report -m --omit=tests/run_tests.py

jobs:
  include:
    #- stage: test
    #  python: 2.7
    #- python: 3.4
    #- python: 3.5
    #- python: 3.6
    #- python: 3.7
    #- python: 3.8
    - stage: deploy
      install:
      script:
        - "PACKAGE_VERSION=$(cat patch_ng.py | grep __version__ | head -1 | awk -F= '{ print $2 }' | sed 's/[ \",]//g')"
        - echo "Deploying library version $PACKAGE_VERSION"
        - echo "Tagged in repo as $TRAVIS_TAG"
        - |
          if [[ "$PACKAGE_VERSION" -ne "$TRAVIS_TAG"]]; then 
            echo "Won't deploy a version that doesn't match the tag!"
          fi
          
      deploy:
        provider: pypi
        user: "__token__"
        password: "pypi-AgENdGVzdC5weXBpLm9yZwIkNDA0MjhhMjItZTQyOS00ZjFiLWI1NDItZGVjOGU5NWNiZGFmAAIleyJwZXJtaXNzaW9ucyI6ICJ1c2VyIiwgInZlcnNpb24iOiAxfQAABiDvri5oMJmYntqX2H3yJSS9PT8zDaG7dnfoc-JiEMHhyg"
        server: https://test.pypi.org/legacy/
        skip_existing: true
        on:
          tags: true
          #branch: master
