stages:
  - test
  - name: deploy
    #if: branch = master

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"

install:
  - pip install coverage
  - pip install pypack

script:
  # run tests with coverage
  - coverage run tests/run_tests.py
  - coverage report -m

jobs:
  include:
    - stage: test
    - stage: deploy
      python: 3.8
      script: echo "This is deploy!"

      deploy:
        provider: pypi
        user: "__token__"
        password: "pypi-AgENdGVzdC5weXBpLm9yZwIkNDA0MjhhMjItZTQyOS00ZjFiLWI1NDItZGVjOGU5NWNiZGFmAAIleyJwZXJtaXNzaW9ucyI6ICJ1c2VyIiwgInZlcnNpb24iOiAxfQAABiDvri5oMJmYntqX2H3yJSS9PT8zDaG7dnfoc-JiEMHhyg"
        server: https://test.pypi.org/legacy/
        skip_existing: true
        on:
          tags: true
          #branch: master
